name: Static analysis, test and build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '*.json'
      - 'packages/app/**'
  push:
    paths:
      - '*.json'
      - 'packages/app/**'

jobs:
  Validate:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Static analysis (ESLint)
        run: pnpm run lint -w=app

      - name: Check types (tsc)
        run: pnpm run check-types -w=app

      - name: Unit tests
        run: pnpm test -w=app

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests

      - name: Build
        run: pnpm run build -w=app
