name: Static analysis, test and build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '*.json'
      - 'packages/app/**'
  push:
    paths:
      - '*.json'
      - 'packages/app/**'

jobs:
  Validate:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Static analysis (ESLint)
        run: npm run lint -w=app

      - name: Check types (tsc)
        run: npm run check-types -w=app

      - name: Unit tests
        run: npm test -w=app

      - name: Build
        run: npm run build -w=app
