name: Static analysis, test and build

on: [push, workflow_dispatch]

jobs:
  install-and-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

  static-analysis:
    runs-on: ubuntu-latest
    needs: install-and-setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'

      - name: Lint (ESLint)
        run: npm run lint

      - name: Check types (tsc)
        run: npm run check-types

  test-and-build:
    runs-on: ubuntu-latest
    needs: install-and-setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'

      - name: Unit tests
        run: npm test

      - name: Build
        run: npm run build
